#include $(srctree)/drivers/misc/mediatek/imgsensor/src/Makefile.custom

#ccflags-y += -I$(srctree)/drivers/misc/mediatek/imgsensor/src/common/v1_1/camera_hw/

obj-y += ov16880mipiraw_Sensor.o
obj-y += ov16880mipiraw_otp.o
obj-y += kd_camera_hw.o
